language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
  - composer self-update
  - composer validate --ansi

install:
  - rm composer.lock
  - travis_retry composer update --prefer-dist